services:
  redis-stack:
    image: redis/redis-stack:7.2.0-v18
    container_name: dbms-251-redis
    ports:
      - "6379:6379"   
      - "8001:8001"   
    volumes:
      - redis_data:/data   
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data:
